# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpaceXFan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpaceXFan
pod 'IQKeyboardManagerSwift'
pod 'SVProgressHUD'
pod 'TTTAttributedLabel'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Auth'
pod 'SDWebImage','5.7.0'



  target 'SpaceXFanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpaceXFanUITests' do
    # Pods for testing
  end

end
